In [ ]:
import numpy as np
a = [1,2,3,4]
type(a)

list

In [ ]:
arr=np.array(a)
print(arr)

[1 2 3 4]


In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
prr = np.array((5,6,4))
prr

array([1, 3, 5])

In [ ]:
b = np.array([1,4,5])
b

array([1, 4, 5])

In [ ]:
arr[0]     #index 0 in the array arr is 1.

1

In [ ]:
prr[1]     #index 1 in prr is 6.

6

In [ ]:
type(arr)    # <class 'numpy.ndarray'>

numpy.ndarray

In [ ]:
c = [5,6,7.8]     #List is heterogenous in nature, it can have elements of different data types.
c               #In list the data type of elements will be same as in the input

[5, 6, 7.8]

In [ ]:
crr = np.array((5,6,7.8))    # In array the input can contain elements with different data types but in the output the array,
crr                        # convert the data types of elements to a single convenient one. (as shown in the output here)

array([5. , 6. , 7.8])

In [ ]:
drr = np.array((5,7.5,'a'))
drr

array(['5', '7.5', 'a'], dtype='<U32')

In [ ]:
arr1 = np.array([1,2,3],dtype=float)
arr1                   # Here, all the elements of array are converted into 'float' because we gave the dtype as float. 

array([1., 2., 3.])

In [ ]:
zrr=np.array([1,2,4,7],dtype='f')      #Other Symbols used for data types:- int->‘i’, uint->’u’,float->’f’,double->’d’,complex->’D’,bool->’b’
zrr

array([1., 2., 4., 7.], dtype=float32)

In [ ]:
a*2        # a=[1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
crr*2    # crr=np.array((5,6,7.5))   Here, array converts the data type to float multiplies each item by 2

array([10. , 12. , 15.6])

In [ ]:
crr**2      # '**' means power but this dont work on List

array([25.  , 36.  , 60.84])

In [ ]:
arr1*2

array([2., 4., 6.])

In [ ]:
arr**2

array([ 1,  4,  9, 16])

In [ ]:
a**2       # As stated above, '**' dont work with list type

TypeError: ignored

In [ ]:
prr+crr    # this will add each element of prr and crr with same index number 

array([10. , 12. , 11.8])

In [ ]:
crr+arr1      # crr = (5,6,7.5)  and  arr1 = (1,2,3)

array([ 6. ,  8. , 10.8])

In [ ]:
# arr = [1,2,3,4]
arr.shape   # shape is a tuple that always gives dimensions of the array. Here, array has only 1 dimension and that contains 4 elements called one dimensional array.

(4,)

In [ ]:
arr.ndim    # Gives Number of array dimensions.

1

In [ ]:
arr.itemsize   # memory occupied by one array element in bytes.

8

In [ ]:
arr.shape*arr.itemsize

(4, 4, 4, 4, 4, 4, 4, 4)

In [ ]:
arr.size*arr.ndim  #Here, ndim is 1

4

In [ ]:
arr.size*arr.itemsize

32

In [ ]:
brr=np.array([1,2,3,4],dtype='int8')
brr.itemsize

1

In [ ]:
m1=np.zeros((3,3))   # Here, a zero or null 3 by 3 matrix is printed whose data type is float.(default data type is float) 
m1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
m3=np.ones((3,3))    # Here, a unit (3 by 3) matrix(every element is 1) is printed and default data type is float. 
m3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
m4=np.ones((3,3),dtype=int)   # Here, we changed the default data type for the matrix to int.
m4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
m1.shape

(3, 3)

In [ ]:
m2=np.eye   # 'eye' is the function for identity matrix.
m2          # Return a 2-D array with ones on the diagonal and zeros elsewhere.

<function numpy.eye>

In [ ]:
m2=np.eye(3)     # Here, this will print an identity matrix.
m2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
mm=np.array([ [1,2,3],[4,5,6],[7,8,9] ])    # 3 by 3 Matrix with user defined elements.
mm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mm[0]        

array([1, 2, 3])

In [ ]:
mm[2]

array([7, 8, 9])

In [ ]:
mm[-1]

array([7, 8, 9])

In [ ]:
mm[0],[0]

(array([1, 2, 3]), [0])

In [ ]:
mm[0,0]

1

In [ ]:
mm[[0],[0]]

array([1])

In [ ]:
mm[0][0]

1

In [ ]:
mm[:,0]

array([1, 4, 7])

In [ ]:
mm[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
mm[:,0:3]     # Also can be written as, mm[:,0:2+1] and mm[:,0:4-1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mm[:,0:-1]      # Also can be written as, mm[:,0:3-1] and mm[:,0:2] and mm[:,0:2:1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
mm[:,-1:0]

array([], shape=(3, 0), dtype=int64)

In [ ]:
mm[:,0:2-1]

array([[1],
       [4],
       [7]])

In [ ]:
mm[:,0:3:2]     #slicing or step shift

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
arr=np.arange(10)        # To print an array with range from 0 t0 9 because 10 is exclusive 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=arr[:-1]        # Here, ':-1' is used for slicing by step shift so it will just remove the last element i.e. 9 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
brr=np.arange(1,10)     # To print an array with range from 1 to 9 because upper limit (10) is exclusive and lower limit (1) is inclusive 
brr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
brr.reshape(3,3)     
# Returns an array containing the same data with a new shape. (Changes the dimensions of the array with accordance of the given input by the user)
# (but we need to put appropriate parameters as argument, if we try to make a matrix that can't be created with the given elements, error will occur.) -> {as in the next cell}
# Unlike the free function 'numpy.reshape', this method on ndarray allows the elements of the shape parameter to be passed in as separate arguments.
# Also, this code did'nt change the actual shape of brr in the memory(it not saved) as we have not assigned any variable to this function yet.
# So, if we print brr the one dimensional array will be printed from 1 to 9 as that is saved in the memory. (shown in cell nxt to below one)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
brr.reshape(4,4)    # Here, brr array has only 9 elements so only (3 by 3) or (3 by 1) or (1 by 3) are the only matrices that can be created. 

ValueError: ignored

In [ ]:
brr  # Here, we printed brr after the reshape function still it gives original 1 dimensional array as brr array was created because reshape is not saved.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
brr=brr.reshape(3,3)    # Here, we saved the reshaped brr array by assigning it a variable 'brr', so now the shape of brr is actually changed in the memory.
brr                     # Now we printed brr and it gave 2 dimensional array as after reshape function.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
brr[0]      # print the 1st row of matrix

array([1, 2, 3])

In [ ]:
brr[0][:]     # [0] is the index for 1st row of matrix and ':' is for whole row from index 0 to 2 within the row.
# Here, 1st [] is to access a particular row and then 2nd [] is for performing any function within that particular accessed row.

array([1, 2, 3])

In [ ]:
brr[0][-3:-1]    # In the 1st row, print from -3 index(means, from 1st element) to -1 which is exclusive so that means upto 2nd element i.e. 2
#Here, [n][a:b] this only works when a & b are in increasing order means b>a which is true above. (won't work in decreasing order) 

array([1, 2])

In [ ]:
brr[0][2:1]   # array is empty as decreasing order in parameters is used.

array([], dtype=int64)

In [ ]:
brr[0][0:3:1]  

array([1, 2, 3])

In [ ]:
brr[0][::-1]     # Here, we reversed the row.

array([3, 2, 1])

In [ ]:
arr=np.arange(1,4)
arr

array([1, 2, 3])

In [ ]:
brr@arr    # Matrix mulplication (multiply each element with corresponding element and then add the multiplied ones) but with row of arr to each row of brr 

array([14, 32, 50])

In [ ]:
np.multiply(arr,brr)     # Just multiplication of corresponding elements of both matrix means row elements of arr multipied with each row one by one of brr.

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [ ]:
np.dot(arr,brr)       # dot product of both matrices

array([30, 36, 42])

In [ ]:
np.cross(arr,arr)    # cross product of arr

array([0, 0, 0])

In [ ]:
crr=np.arange(9).reshape(3,3)     #creating a 1 dimensional array and changing shape of that using one function.
crr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
brr*crr       # product of each element of brr with corresponding element of crr.

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])