In [ ]:
import numpy as np
arr=np.arange(0,24)     
b=arr.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[...,0,0]

array([ 0, 12])

In [ ]:
b[:,0,0]

array([ 0, 12])

In [ ]:
b[0,1,0:3:2]

array([4, 6])

In [ ]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
b[...,0,:,1]

array([1, 5, 9])

In [ ]:
b[...,0,:,3]

array([ 3,  7, 11])

In [ ]:
b[...,0,::-1,3]

array([11,  7,  3])

In [ ]:
b[...,0,0:3:2,3]

array([ 3, 11])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
import numpy as np
m1=np.arange(0,9).reshape(3,3)    
m2=np.array([[1,0,2],[0,4,3],[9,1,1]])
np.dot(m1,m2)

array([[18,  6,  5],
       [48, 21, 23],
       [78, 36, 41]])

In [ ]:
np.multiply(m1,m2)

array([[ 0,  0,  4],
       [ 0, 16, 15],
       [54,  7,  8]])

In [ ]:
arr2=np.arange(1,10)
minimum=np.min(arr2)
minimum

1

In [ ]:
maximum=np.max(arr2)
maximum

9

In [ ]:
avg=np.average(arr2)
avg

5.0

In [ ]:
import numpy as np
arr1 = np.arange(1,5)
arr2 = np.arange(5,10)
np.concatenate((arr1,arr2),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((m1,m2),axis=1)

array([[0, 1, 2, 1, 0, 2],
       [3, 4, 5, 0, 4, 3],
       [6, 7, 8, 9, 1, 1]])

In [ ]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'float128', 'f16', 'complex64', 'c8', 'complex128', 'c16', 'complex256', 'c32', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_'

In [ ]:
A=np.array([[0, 1], [2, 3],[4, 5]]) 
A.astype(float) 

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [ ]:
A.astype(bool)

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [ ]:
record=np.dtype([('name',str,40),('no_of_items',int),('price','float64')]) 
record

dtype([('name', '<U40'), ('no_of_items', '<i8'), ('price', '<f8')])

In [ ]:
items=np.array([('life of dvd',42,30.50),('Butter',10,22.75)], dtype=record)
items

array([('life of dvd', 42, 30.5 ), ('Butter', 10, 22.75)],
      dtype=[('name', '<U40'), ('no_of_items', '<i8'), ('price', '<f8')])

In [ ]:
import numpy as np
arr=np.arange(0,24)     
b=arr.reshape(2,3,4)
b=b.T
b

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'float128', 'f16', 'complex64', 'c8', 'complex128', 'c16', 'complex256', 'c32', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_'